apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    app: nginx-server
    tier: backend
spec:
  selector:
    tier: backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer