apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    app: nginx-server
    tier: backend
spec:
  selector:
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 80
      name: https