apiVersion: v1
kind: Service
metadata:
  name: nginx-server-np
spec:
  selector:
    app: nginx-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 80
      name: https