apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-server
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
      version: green
  template:
    metadata:
      labels: 
        app: nginx-server
    spec:
      containers:
      - image: nginx:1.19.5
        name: nginx-green
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
