apiVersion: v1
kind: Service
metadata:
  name: nginx-bluegreensvc
spec:
  selector:
    version: v1.0.0
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: https