apiVersion: v1
kind: Service
metadata:
  name: nginx-bluesvc
spec:
  selector:
    app: nginx-blue
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: https