apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ramped
  labels:
    app: nginx-ramped-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
      name: nginx-v2
    spec:
      containers:
      - image: marbellacovino/nginx:1.0
        name: nginx
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"